### ISSUE TITLE
Shift names that extend into the next day are truncated and possibly unreadable

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#116]
I have a midnight ice shift from 11:30pm to 12:30am (for delivering ice to theme camp bars). 

Since the volunteering scheduling calendar cannot scroll between days the name of the shift (ex. Thu Midnight Ice) is truncated and unreadable (and will thus be difficult for vols to signup for if they are attempting to do so from within the system). 

![image](https://user-images.githubusercontent.com/3332990/159656404-74591885-dc20-48f7-bf3c-74d6cde3b454.png)

**Comment by pboyd04** [comment]
Mouse over will reveal the full shift details. Also the list view can be used if desired (or on a phone (default)) 
![image](https://user-images.githubusercontent.com/594097/160249384-fd20f351-243e-4f70-9ec4-9370025f5972.png)
