### ISSUE TITLE
Fix display of name with nickname

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#121]
At the early-entry approval list, names are displayed as Firstname "Nickname" Lastname.

If the person has no nickname, this is displayed Firstname " " Lastname. Also, trailing spaces are not stripped out.

https://secure.burningflipside.com/fvs/_admin/ee.php

**Comment by pboyd04** [comment]
Fixed, also now handles the case where firstname = burner name
