### ISSUE TITLE
Shifts disappearing from shift set after creation. 

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#123]
Created a "Tues TEST Shift" (5/24 from 11:30AM to 6PM) containing 8 total individual shifts (Shift Lead, Cashier x2, Slinger x2, Pusher x2, Camp Contact) and, after the shift had been created, disabled the shift (marked un-enabled). 

Returned to Add/Edit Shifts to find the shift had been downsized to 3 positions (Cashier, Slinger, Pusher). 

I was able to reproduce this a second time by creating a shift SET with multiples of the same position (11 total this time, Shift Lead, Camp Contact, 3x of Cashier, Slinger, Pusher each) and following the same procedure as above (editing the shift after creation by un-enabling) and again the system seemed to downsize each position by a single shift - leaving me with a set containing only 2x Cashier, Slinger, Pusher (Shift Lead and Camp Contact have been removed)

This behavior isn't completely consistent but seems to be triggered either by multiples of the same role in a shift set and/or a shift being edited after creation.

**Comment by monikersupreme** [comment]
I think this may be related to the issue Catherine Reynolds reported a few days ago:

'Catherine Reynolds' via Leads | 'Catherine Reynolds' via Leads | Mar 26, 2022, 1:51 PM

and may be the cause of the shifts she lost as well.

**Comment by monikersupreme** [comment]
Also seeing an error message whenever I attempt to edit a shift set:

![image](https://user-images.githubusercontent.com/3332990/160692927-f54fbee7-f197-4551-9088-3d5d5320c4bb.png)

**Comment by monikersupreme** [comment]
Steps to reproduce:

Set up a shift set with multiple shifts for each role:

![image](https://user-images.githubusercontent.com/3332990/160694559-4f00bb1f-b8ee-42d4-b07b-5762067ed72d.png)

Open the shift for edit - I've been toggling the Enabled check box each time but I've actually got this to reproduce without making any changes at all - then select "Save Shift Set":

![image](https://user-images.githubusercontent.com/3332990/160694906-f6922c1d-ef66-4192-879e-75138a5f99fc.png)

Doing this same procedure multiple times can sometimes result in the shift set getting deleted altogether.

**Comment by pboyd04** [comment]
Fixed
