### ISSUE TITLE
Remember filtering preferences

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#127]
When viewing shifts by departments, remember which departments you have previously used to filter the view, and automagically repopulate that. 
<img width="1050" alt="Screen Shot 2022-04-04 at 11 40 05" src="https://user-images.githubusercontent.com/15695982/161591288-b992947f-ab1b-49df-86aa-c9b5b006c065.png">

**Comment by pboyd04** [comment]
Fixed
