### ISSUE TITLE
Badly cropped cert image

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#129]
<img width="803" alt="Screen Shot 2022-04-08 at 17 20 48" src="https://user-images.githubusercontent.com/15695982/162541602-a6da7736-260f-4022-a20f-339b6e7b25f9.png">
This is in the "certification approval" queue.

**Comment by pboyd04** [comment]
Just click on the image. It will pull up the full sized image. Only so much I can cram into the table.

**Comment by adamjrice** [comment]
For me, only the first cert (for Sam) is clickable. This is in a vanilla installation of Chromium.

**Comment by pboyd04** [comment]
Ah it's a weirdness with PDFs. You basically need to click around the edge of anything that was uploaded as a PDF

**Comment by adamjrice** [comment]
Ah. That works. Requires a fine touch!

**Comment by pboyd04** [comment]
This should be better now. Please test it on your browser. It should render as a HTML5 canvas now which allows clicking everywhere. I left the rendering in the dialogs as native PDF since it probably works a bit better...

**Comment by adamjrice** [comment]
Confirmed!
