### ISSUE TITLE
Individual shifts in set appear as taken even though the shift is empty. 

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#132]
I've checked on a couple different browsers just in case there was some sort of caching issue but it's showing up on both. 

From my admin view:

Tues TEST Shift-7 on the calendar:
![image](https://user-images.githubusercontent.com/3332990/163061657-83c09670-3a3c-4199-81ed-6ca2d6639336.png)

Tues TEST Shift-7 in Add/Edit Shifts:
![image](https://user-images.githubusercontent.com/3332990/163061013-242e22b5-9db8-46eb-b763-e5ba13ebe845.png)

**Comment by pboyd04** [comment]
There is a pending group signup for that shift (i.e. you didn't abandon that signup for the entire group). This is expected behavior. "status": "groupPending",

**Comment by monikersupreme** [comment]
So I would need to delete the group signup link and generate a new one?

**Comment by pboyd04** [comment]
groupPending means it is waiting for someone to signup for a group shift. That doesn't show up in the pending report.
