### ISSUE TITLE
As a volunteer using a group link sign-up, it would be helpful to have info regarding the specific shift I am linked to

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#134]
If the specific shift set name, time, day, dept were include in the sign-up page that would be helpful

![image](https://user-images.githubusercontent.com/3332990/163068255-356ae498-90d5-49f9-b0b8-03aa08996a31.png)

**Comment by pboyd04** [comment]
Added the same data that is on the regular sign up page.
