### ISSUE TITLE
Proposed report: volunteers without tickets

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#135]
I also suggest adding columns to the report showing departments where they're volunteering (if they're signed up for any shifts at all) and number of shifts.

**Comment by pboyd04** [comment]
Added: https://secure.burningflipside.com/fvs/_admin/report_no_ticket.php

**Comment by adamjrice** [comment]
This is weird
<img width="1117" alt="Screen Shot 2022-04-16 at 14 41 36" src="https://user-images.githubusercontent.com/15695982/163689221-fb493456-4663-4629-a412-2dea040915be.png">
:

**Comment by pboyd04** [comment]
/dev/null is what gets put in if a lead signs up a shift without putting anyone in it. There is a giant warning dialog to not do it basically, but I do let them...
![image](https://user-images.githubusercontent.com/594097/163691306-c22dc27b-35cc-4880-b146-a3cb66d1fec4.png)
