### ISSUE TITLE
Volunteer Contact and Profile Info is allowing capitalized email addresses and mismatching bc of case-sensitive context

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#136]
When I attempt to assign irismuscarella@yahoo.com a volunteer shift I get:

![image](https://user-images.githubusercontent.com/3332990/164815728-efecae37-8055-4c7c-84f4-c80761752756.png)

I think this is because the first letter 'I' of her email address is capitalized in the FVS table.  

![image](https://user-images.githubusercontent.com/3332990/164815573-975fc618-3979-4dc0-8314-69181084fb8c.png)
 
Either email addresses should either automatically be lowercased or searches should probably not be case sensitive.

**Comment by monikersupreme** [comment]
Also whitespace - if I have an extra space at the end of an email the match will fail.

**Comment by pboyd04** [comment]
Fixed, it now does a case insensitive search and removes spaces from the input.
