### ISSUE TITLE
As a lead I want to be able designate certain volunteers as critical volunteers

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#40]
This exempts them from any ticket lottery.

**Comment by pboyd04** [comment]
1. It could exempt them from the lottery if used before ticket opening.
2. It could also be used as a report both by AAR trying to sell crit vol tickets and AFs/Leads to tell them which volunteers they have that absolutely need tickets
3. It can help us with history when determining ticket margins "Well last year we had X critvol tickets, so this year we should prepare for Y"
