### ISSUE TITLE
Janky pseudo-menu on New Shift Group pseudo-window

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#77]
Width seems to be dictated by first menu item, which is very short in this case. Horizontal scrollbars will appear.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/15695982/74059062-f1e8f480-49ac-11ea-870f-0a4987771071.png">

**Comment by adamjrice** [comment]
When I returned to this pseudo-window after posting this, the menu was the correct width. Go figure.

**Comment by pboyd04** [comment]
Ok I've made this so that it should be better.
