### ISSUE TITLE
Possible confusion between "group shifts" and "shift groups"

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#78]
Maybe change the name of one or the other to avoid this, so "group shifts" could be "collective shifts" or "shift groups" could be "shift sets"?

**Comment by ed-cosmos** [comment]
CONCUR!!! I was reading Adam's help on this section, and it was super difficult to keep straight

**Comment by pboyd04** [comment]
Ok I've change the name to shift sets. I think I got everywhere

**Comment by adamjrice** [comment]
"New Shift Group" popover is still a "shift group"

**Comment by pboyd04** [comment]
Fixed
