### ISSUE TITLE
Difficulty grouping shifts

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#79]
- I created 3 copies of a shift.
- I merged two instances into a shift group. This worked.
- I opened the newly created shift group and attempted to merge the 3rd standalone shift. Nothing happened when I clicked the button to merge.
- I opened the 3rd standalone shift and merged it with the new shift group. This worked.

**Comment by pboyd04** [comment]
I've fixed this. Want to verify and then close the issue?

**Comment by adamjrice** [comment]
Seems to work.
