### ISSUE TITLE
"Participant shifts" report filtering not accurate

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#82]
Currently shows a nameless volunteer with multiple shifts, other volunteers who have shifts in departments other than the selected department.

**Comment by adamjrice** [comment]
Also, "Participants without shifts" shows some of the same volunteers who have a shift count > 1

**Comment by pboyd04** [comment]
Ok fixed. Take a look and close.

**Comment by adamjrice** [comment]
Not as serious, but switching from a department that has >0 filled shifts to a department that has 0 filled shifts does not update the list of volunteers here.

**Comment by pboyd04** [comment]
Ok fixed that too
