### ISSUE TITLE
Wrong dates in date picker for new shift, but not shift group

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#85]
Attempted to create Line Sweep shifts for post-event cleanup.

Initially created a shift group. That worked fine, but I realized I did not want it to be a shift group, so I deleted the group.

Then attempted to create a plain shift with unbounded signups. The date picker showed me Feb 14-16 as the available dates (that is, Work Weekend I).

Tried this in Safari and Firefox, just to minimize effects of JS weirdness.

**Comment by pboyd04** [comment]
This is working fine on my copy of Firefox and Chrome. Are you sure you changed the event for the shift to the cleanup weekend?

**Comment by adamjrice** [comment]
![Screen Shot 2020-02-09 at 17 22 30](https://user-images.githubusercontent.com/15695982/74112279-ceff4180-4b60-11ea-9a08-cbb05b6e6c94.png)

**Comment by pboyd04** [comment]
Ok I've fixed the workaround for Safari/Firefox.
